services:
    kernel.listener.your_listener_name:
        class: forumhulp\errorpages\event\listener
        arguments:
            - @log
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
